[build]
  command = "hugo --gc --minify -b $URL --themesDir ../../"
  publish = "public"

[build.environment]
  HUGO_THEME = "repo"
  HUGO_VERSION = "0.55.6"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"

  [context.deploy-preview.environment]
    HUGO_VERSION = "0.20"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL --themesDir ../../"
  HUGO_VERSION = "0.55.6"
